### ISSUE TITLE
Invoke a change during MIPS iterative process

### ISSUE THREAD

**Issue by Admibida** [MATPOWER/mips#6]
Hello there, 

I have a question regarding the Newton iterations inside the MIPS solver (mips.m). 
The solver starts with an initial state of the optimization vector x(0) and then it calculates whatever is needed in order to update the  value of x to x(i+1)=x(i)+dx(i) and repeat the process untli the KKT conditions are satisfied, according to the given tolerance. For instance, if it iterates 10 times in order to converge, that means the optimization vector was updated 10 times until the solution was reached. 

Lets say that, during this process, I want  to achive the following:
**Ιf the voltage Vm(i) of a given PV bus  is approaching its Vmax, I want to "command" a specific generator to allocate its reactive power in such way, that the voltage rise is tackled.** 

However, when Vm(i) reaches this critical value, and I explicitely modify the x(i) row that represents the Qg(i) of the specific generator,  it seems that the dx(i) has always such value that it guides the x(i+1) back to the value that it would have anyway (without making any modification to the original code) and always reaches the same objective function value. 
Does this happen because the objective function is set to minimize the reactive power cost as well and no matter what change I invoke to Qg it will always guide the solution towards min gencost?

Does it sound to you like something that can be done by using this approach or an alternative one?
Thanks a lot,

**Comment by rdzman** [comment]
The default objective is to minimize the total generation cost. Usually this also means dispatching Q in such a way that voltages are increased to reduce system losses.

If you modify values of _x_ inside `mips()` during the iteration process, it is simply like giving it a new point from which to continue pursuing the same objective.

If there is another objective you would like to pursue, you need to find a way to include it explicitly in the objective function, then MIPS should just find it for you.

**Comment by Admibida** [comment]
Thanks a lot for the response,
 It totally makes sense. The difficulty of my problem is that I dont wish to minimize voltage variation for the whole system that can be explicitly added in the objective function. 
Wherever a voltage of a certain PV bus reaches a critical lower or upper value, I want the specific generator to dispatch as much reactive power it needs to tackle the voltage drop or rise of this bus and this bus only (assuming that there is no reactive cost assigned to it and thus it can provide as much as it is technically possible without affecting the generation cost, at least directly). 
Do you think that there is a simple way to formulate it within the objective function?

**Comment by rdzman** [comment]
I'm afraid you problem might not be well-posed yet. You may need to clarify a bit more precisely what your goal is. Some of the description is unclear.

For example, what do you mean by a voltage "reaches" a limit? Until MIPS converges to an optimal solution, the values of _x_ do not necessarily satisfy even the power flow equations. So, It's not like you are tracing out some path of feasible operating points and at some point a voltage "reaches" a limit and you can activate a specific control prevent a limit violation. That sounds more like a power flow with controls, not an OPF.

In the OPF, everything is tied to everything ... all voltages are affected by all injections and vice versa. You can prefer reactive power from one generator over another by putting costs on their reactive injections to reflect that. But that will impact voltages everywhere.

Maybe you want to look at some sort of optimal **change** from a given operating point with voltage violations to a feasible point, where only a few controls are available?

Or maybe you want to look at a path from one operating point to another that would result in a violation *unless* some control action is taken?

Just trying to give you some ideas to help you formulate your problem more precisely.

**Comment by Admibida** [comment]
I want a specific generator to act as a typical PV bus in all instances except when the voltage is approaching its Vmax limit. For instance, lets consider that Vmax=1.05 p.u.  If the voltage is on the verge of surpassing 1.04 p.u. I want the generator to take specific action and instantly provide its maximum reactive power while keeping the same active power output with the target of preventing the bus voltage to eventually reach 1.05 p.u. The system is a distribution network. 

That means that, at this instance, the reactive power is fixed to its maximum value and thus is not free for the solver to calculate in order to minimize the objective function. As if all system buses allocate their power output in order to minimize the total cost except this one that decides on its own to take action when the voltage threshold of 1.04 gets violated. 

If voltage is lower than 1.04, then it behaves like all other buses but if it surpasses 1.04, its primal goal is to tackle the bus voltage rise by allocating its reactive power accordingly  (as for now we assume that there is no reactive power cost assigned and thus its pursuit to tackle voltage rise doesnt directly contradict the objective function of the optimization problem).  
Your last suggestions seems closer to my general idea, i.e. unless a specific control action is taken, then the solution would lock up to the upper limit Vmax, so try to reach an operating point that doesnt result to this violation. However, we decide the amount of reactive power that it will provide at this operating point and not the solver. The solver shall take this reactive power for granted, while trying to satisfy the objective function. As if when Vmin<Vbus<Vcrit,max, then Qmin<=Qg<=Qmax (standard case and solver decides its value) BUT when Vcrit,max<=Vbus<Vmax  then we explicitly set Qmin=Qmax=Qg (we determine a specific Qg according to some personal criteria)

**Comment by rdzman** [comment]
You lost me with the first sentence. In the OPF, there is no such thing as a PV bus ... both P and V are optimization variables. Now, they can be fixed at a set-point, as in a power flow, by setting PMIN = PMAX = specified value, and VMIN = VMAX = specified value.

And again, using the words "approaching" and "surpassing" give the idea that you are thinking of some progression here, not a solution to a static problem. If the progression you are talking about is the progression of the iterates in the MIPS interior-point algorithm, then once again, I would point out that these values do not represent actual operating points of the system, since even the power balance constraints are not satisfied until a solution is found.

Another thing is that injecting reactive power tends to increase voltage magnitude, not decrease it. So you would want to increase reactive power to deal with a lower voltage limit, not an upper voltage limit.

Am I correct in assuming that what you are really trying to find is the result of applying a single reactive power control to a system with a particular bus voltage violation? That is, you solve your original OPF with the 1.05 limit, then if the voltage exceeds 1.04, you want to apply a particular reactive power control and solve for the resulting solution?

If so, it sounds like the second problem is simply a power flow, where all generators use the P and V set points coming from the OPF solution, except at the generator(s) where you want to fix the voltage or apply the reactive power control. Those buses would be set to PQ buses with the reactive power dispatch determined by you.

Does that sound like what you want?

**Comment by Admibida** [comment]
Yes, thank you very much
